name: cardsproject2
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5 #GetX State Manager
  get_storage: ^2.0.3 #GetX Local Storage Manager
  flutter_onboarding_slider: ^1.0.8 #Page Slider (On Boarding)
  flutter_svg: ^1.1.6 #Draw SVG Files

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: ibm_plex_sans_arabic
    - fonts:
      - asset:  fonts/ibm_plex_sans_arabic.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
