name: cardsproject2
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5 #GetX State Manager
  get_storage: ^2.0.3 #GetX Local Storage Manager
  flutter_onboarding_slider: ^1.0.8 #Page Slider (On Boarding)
  flutter_svg: ^1.1.6 #Draw SVG Files
  otp_text_field: ^1.1.3 #OTP Text Field
  timer_count_down: ^2.2.2 #CountDown Timer
  persistent_bottom_nav_bar: ^5.0.2 #Bottom Navigation Bar
  dropdown_button2: ^2.1.3 #Dropdown Button
  http: ^1.1.0 #Http Client
  firebase_messaging: ^14.6.7 #Firebase Messaging 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: ibm_plex_sans_arabic
    - fonts:
        - asset:  fonts/ibm_plex_sans_arabic.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
